OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-g0b26cf6f08ef80642b4a96c4d6fdef341d75a40a4eRtQWT"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"
  target_language: "Spanish"